### ISSUE TITLE
Add number formatting

### ISSUE THREAD

**Issue by pandurijal** [monacook/Covid.Tracker#13]
Hello there. It seems like you pass the number directly to the table's cell without any formatting, while it's better to use some kind of three-digits-formatting to make users easier to read. Can I work on this issue?

**Comment by monacook** [comment]
Sure! Go for it. Let's see what you got and then just send me a PR when you are done.

**Comment by monacook** [comment]
@pandurijal Can you explain a bit more? I created a table component then passed the data from the child to the parent. This was practice of passing data through components.

**Comment by pandurijal** [comment]
What I mean is you literally put the data like this: `12723989`, while isn't it easier to read if displayed like `12.723.989` this?

**Comment by monacook** [comment]
Oh! You mean put the number as a string to create 12723989 to 12,723,989. Correct? I read the 12.723.989 as an IP address for some reason. The periods through me off.

**Comment by pandurijal** [comment]
Hahaha yes sorry for making you confused. How about that? Is it okay if I contribute to this project through this issue?

**Comment by monacook** [comment]
Sure! Go for it. Just make sure to create a new branch from the master and then once you are done, don't merge it, just send me a PR to code review your code and then will go from there. :)

**Comment by pandurijal** [comment]
Aight will do! :))
